specs/language/CMakeLists.txt, specs/language/glossary.tex, specs/language/hlsl.tex, specs/language/introduction.tex
This stubs out some LaTeX goop and a first stab at the Introduction for an HLSL Specification.
I'm sure LaTeX isn't everyone's preferred format, but it is git-friendly and supports all the formatting bells and whistles we might need.
=> Initial HLSL Specifiction LaTeX stub

proposals/0008-non-member-operator-overloading.md, proposals/NNNN-non-member-operator-overloading.md
This proposal enables users to work around one of the challenge points they've reported adopting HLSL 2021, while allowing the language to remain moving forward.
=> Proposal for non-member operator overloading

proposals/0009-math-modes.md
The new HLSL math modes aims to provide an alternative to the `precise` attribute which will both be less bug prone and provide a higher degree of control for developers.
=> Initial proposal for math modes

.github/ISSUE_TEMPLATE/proposal.md, .github/ISSUE_TEMPLATE/spec.md, docs/Process.md
These templates are for helping file spec issues and proposal follow-up issues so that we can better track proposals as they are being developed.
=> Add new issue templates

proposals/0010-vk-buffer-ref.md
Create a new first class type vk::BufferPointer which allows users to efficiently reference buffer device addresses and allows tools to analyze and report on usage in a logical rather than physical way i.e. names rather than numeric offsets.
=> Add vk::BufferPointer to HLSL

proposals/0010-vk-buffer-ref.md
=> Add type punning rules to vk::BufferPointer

proposals/0010-vk-buffer-ref.md
=> Add writability to vk::BufferPointer pointees

proposals/0010-vk-buffer-ref.md
I used the existing HLSL practice of using the new type name as the name of the casting method. I did not add a vk::pointer_cast<>() method. If there is an advantage to such a method, I am open to it.
Fixes #44
=> Add casting to buffer pointer proposal.

proposals/0010-vk-buffer-ref.md
=> Specify aliasing and address space for vk::BufferPointer

specs/language/basic.tex, specs/language/conversions.tex, specs/language/hlsl.tex
This change adds some basic language to describe values then moves into describing HLSL's standard conversions and standard conversion sequences.
=> Start specifying standard conversions

specs/language/hlsl.tex, specs/language/lex.tex, specs/language/macros.tex
This change adds some macros to format grammar definitions similar to how the C++ standard does. It then uses the new macros in the new lexing sections for:
* Character Sets
* Preprocessing Tokens
* Tokens
* Comments
* Header Names
This is all extremely consistent with C/C++ circa 2011. The deviations will start in the next sections.
[Updated draft PDF](https://github.com/microsoft/hlsl-specs/files/13275380/hlsl.pdf)
=> Basic lexing for preprocessor tokens

proposals/0010-vk-buffer-ref.md
Specifically, clarify interaction with default (restrict) BufferPointer.
Fixes #87.
=> [0010] Clarify behavior of vk::aliased_pointer on vk::BufferPointer

specs/language/hlsl.tex
The hyperref package makes table of contents entries clickable, makes the contents sidebar work, and lets `\ref` make clickable links.
=> Add table of contents sidebar and links to HLSL spec (hyperref)

.github/workflows/jekyll-gh-pages.yml
There is a bug in pandoc-2.9 that causes it to fail processing the language spec. The issue is resolved on pandoc-3.1 which is not currently in the Ubuntu Jammy packages. This change just downloads the release from GitHub and installs it into the VM image.
=> Manually grab pandoc-3.1.9

proposals/0012-psv0-entry-name.md, proposals/NNNN-psv0-entry-name.md
This proposes we add a new EntryFunctionName field for PSV0 to encode the entry name for D3D12 runtime use.
=> Proposal for adding shader function name to PSV0 part

proposals/0012-psv0-entry-name.md
Replace "collections" with "state objects" based on feedback.
=> 0012 feedback - Clarify language from collections to state objects

specs/language/lex.tex
This change stubbs out some secitons in the lexer chapter with commented out section definitions and fleshes out the specific setion for the vector literal grammar.
[PDF of Changes](https://github.com/microsoft/hlsl-specs/files/13298698/hlsl.pdf)
=> Adding lexing specification for vector literals

proposals/0011-inline-spirv.md
NumWorkgroups should be a uint vector with three components.
=> Fix typo in 0011-inline-spirv.md

proposals/0010-vk-buffer-ref.md
=> [0010] Fix description of Get method ie remove const

proposals/0011-inline-spirv.md
In order to better match the semantics of builtin variables, use static variables instead of functions in order to get and set builtins.
=> [0011] Use variable syntax instead of function syntax for SPIR-V builtin

specs/language/hlsl.tex, specs/language/introduction.tex, specs/language/lex.tex, specs/language/placeholders.tex
Declaring placeholder headings allows us to just put the references in as we're writing earlier parts of the document instead of leaving FIXME comments around.
=> Add a file to store placeholder reference points

specs/language/expressions.tex, specs/language/macros.tex
This adds wording for the first three easy categories of primary expressions:
* Literal expressions
* `this` expressions
* Parenthesized expressions
[Updated PDF](https://github.com/microsoft/hlsl-specs/files/13370668/hlsl.pdf)
=> Start section on Primary Expressions

docs/Contact.md, docs/DesignConsiderations.md, docs/Process.md
This update adds new documents on design considerations and contact information.
The design considerations document tries to codify some of the basic design language for HLSL and cover common topics that features will need to address in their specification.
This also updates some wording and details around the process docs and specifically about proposal sponsors. We think it is important that Vulkan-specific proposals have a sponsor from the Vulkan Working Group, so that is explicitly stated.
=> Add design considerations and clarify process

proposals/0010-vk-buffer-ref.md
This statement explicitly contradicts a later statement that says:
> While buffer pointer types are allowed in unions
I believe we landed on allowed buffer pointers in unions, so we will
keep that statement.
=> [0010] Remove statement disallowing unions

proposals/0010-vk-buffer-ref.md
We have decided to allow casting to uint64_t. It will make create
more opportunities for developers to make mistakes, but they do not
have to use it. The implementation cost does not seem too high.
Fixes https://github.com/microsoft/hlsl-specs/issues/93
=> [0010] Allow casting to uint64_t

specs/language/expressions.tex, specs/language/hlsl.tex, specs/language/macros.tex
These are just empty placeholder sections with some grammar definitions to fill in the ID expression grammars. Properly documenting this will require going back and defining scopes and other lexical constructs.
Since all of this is more or less inherited from C/C++ I'm going to leave them as stubs for now and focus on the HLSL-specific sections.
This change also introduces numbered sub-subsections and formatting for optional grammar elements.
=> Add stub grammar definitions and sections

specs/language/expressions.tex, specs/language/placeholders.tex
This adds definitions for HLSL array subscripting. HLSL deviates from C/C++ in part because of the lack of pointers.
=> [Expr] Add Expr.Post.Subscript

.github/workflows/jekyll-gh-pages.yml
Our doc build started failing due to a change in the azure images. The failure is the same as what is reported in this issue: https://github.com/actions/runner-images/issues/7603.
The fix described there is to call `sudo apt-get update`, which is the change here.
=> Fix failing GitHub action to deploy docs

specs/language/expressions.tex
For some reason pandoc doesn't like this formatting.
=> Fix Pandoc build

specs/language/expressions.tex, specs/language/placeholders.tex
This section specifies how HLSL function calls work as well as how argument and paramters are represented, their lifetimes and semantics.
=> [Expr] Add Expr.Post.Call

proposals/0010-vk-buffer-ref.md
This clarifies any ambiguity around atomic operations.
Fixes #88
=> Explicitly state lvalue-reference semantics

.github/workflows/jekyll-gh-pages.yml, specs/language/expressions.tex
This enables the documentation build to run when the LaTeX is modified in a PR.
As initially posted this change includes part of the change from PR #145 so that there is a modified file in the spec to force a build to trigger.
Fixes #143
=> Add pre-merge build

docs/Process.md, proposals/infra/index.md, proposals/templates/infrastructure-template.md
This updates the process docmentation and adds a new template for describing infrastructural proposals. This will allow us to use this process format for desigining project infrastructure and implementation details within the tooling that may not have language or other user exposure.
=> Update process for infrastructural proposals

proposals/0011-inline-spirv.md
`SpirvType` now takes size and alignment as parameters, and a new template `SpirvOpaqueType` is added that does not. Also lets users specify whether a parameter for the type-declaration instruction should take an id or an immediate literal value.
Fixes #128.
=> [0011] Clarify behavior of SpirvType parameters and add SpirvOpaqueType

proposals/0014-wave-size-range.md
Adds the ability to specify a range of wave sizes that a shader can use instead of being limited to just one value
=> Wave size range proposal

proposals/0013-wave-size-range.md
Replaces all mention of literal values with "compile-time constant" values per our decision to expand the allowed values. Note that DXC currently doesn't allow many expected compile-time values to work here, but that's a sparate bug.
Additionally corrected references to "power-of-two" as an adjective to use hyphens.
Fixes #161
=> [Wave Size Range] Allow compile-time constant parameters

proposals/0011-inline-spirv.md
Fix a couple of the examples – global constants must be `static`, attr lists should go before the function declaration, not the template declaration.
@s-perron
=> [0011] Fix invalid example code

proposals/0011-inline-spirv.md
Instead of using an arbitrary unchecked list of parameters, require that `SpirvType` and `SpirvOpaqueType` take a type template parameter pack for the list of operands. For example, now `SpirvOpaqueType` is defined as
```
template<uint OpCode, typename... Operands>
struct SpirvOpaqueType {};
```
A type `vk::integral_constant<typename T, T v>` is defined in order to allow literal values as operands, and a type qualifier _spirv_immediate is defined in order to specify that a literal value should be embedded as an immediate value in the SPIR-V type-declaration instruction.
@s-perron and @llvm-beanz for review.
=> [0011] Make SpirvType take type template parameter pack

proposals/0013-wave-size-range.md
The biggest change here is that the RangedWaveSize tag can have a first element non-zero with the rest zero to represent the old WaveSizeTag behavior. Added some clarification of metadata restrictions and error generation as well.
Fixes #158
=> [Wave Size Range] Revise metadata representation

proposals/0015-extended-command-info.md
Specification for SV_StartVertexLocation and SV_StartInstanceLocation semantics. Documents DXIL and SPIR-V interfaces, new diagnostics, and testing suggestions.
=> Add extended command info spec 

proposals/0016-c-interface-compiler-library.md
One of the HLSL compiler's primary usage modes is as a library. The upstream compiler will also need to expose a library for  toolchains to compile a shader.
This commit introduces a new proposal to add a c-style library for toolchains and other titles to use the HLSL compiler as a library.
The proposal is to address:
Issue#63631
=> Introduce proposal for c style library for HLSL compilation

proposals/0017-conforming-literals.md, proposals/NNNN-conforming-literals.md
This proposal seeks to codfiy the behavior documented in the HLSL documentation
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-appendix-grammar#floating-point-numbers, and captured in #175 as the behavior for HLSL 202x.
=> Add proposal for conforming literals

proposals/0015-extended-command-info.md
Removes irrelevant text from another spec mistakenly copied in.
=> remove stale copy/pasted text

proposals/0017-conforming-literals.md
Need to use full links not shorthand in markdown files.
=> [0017] Fix links to issues and PR

proposals/infra/INF-0001-availability-diagnostics.md, proposals/infra/INF-NNNN-availability-diagnostics.md
This proposal introduces three modes for producing availability diagnostics during semantic analyisis. These diagnostics can be adjusted by the user to control the severity and allow for controlled tightening of rules around API exposure.
=> Introduce proposal for availability diagnostics

proposals/0019-mesh-nodes.md
The mesh nodes spec isn't clear about whether or not derivative operations will be supported. This PR adds a subsection addressed to derivative operation support, and explains why the support is present.
=> Add subsection on derivative operations

specs/language/glossary.tex, specs/language/hlsl.tex, specs/language/introduction.tex
This update Intro.Defs earlier in the introduction and puts more detail into the SPMD programming model and memory model.
The PDF draft of this change is available [here](https://github.com/microsoft/hlsl-specs/files/12552783/hlsl.pdf).
=> Fleshing out Execution and Memory models

specs/language/conversions.tex
This change fixes a spec bug in the description of HLSL truncation casts, restricts the array-to-pointer cast to unbounded arrays (where they decay to pointers), and specifies integral and floating point conversion ranks.
This updates the spec to be more consistent with how the language is being implemented in clang and lays the groundwork for describing overload resolution rules.
=> Update conversion sequences and describe ranks

specs/language/expressions.tex
One part of this is just a whitespace no-op, but putting the \define on its own line fixes some formatting in the PDF to properly indent the item.
=> Fix whitespace

proposals/infra/INF-0001-availability-diagnostics.md
Add details about what the availability diagnostics text should look like based on the target shader stage and model.
Fixes #188
=> [INF-001] Add details on availability diagnostic text

proposals/infra/INF-0003-packoffset.md
Added design doc for packoffset to start the discussion.
Right now, cbuffer llvm IR and metadata is not ready yet.
Need to update the related part once cbuffer got full support.
Also need to decide how to support 16bit types.
=> Add doc for packoffset.

proposals/infra/INF-0003-packoffset.md
Added < !-- {% endraw %} -- > at the end.
=> Fix error caused by missing endraw.

specs/language/basic.tex, specs/language/glossary.tex
This just cleans up the C++ references in the document. It includes the following changes:
* Made the name in the glossaries human readable rather than the ISO/IEC number, and included the year.
* Changed two places where \glsdesc was called to \gls
* Extended the description text to have the ISO/IEC number and full standard title.
* Formalize general C/C++ references to C11 and C++11.
With this change references from `\gls{...}` will expand to a readable name (e.g. "ISO C Standard (2011)") rather than the ISO/IEC number.
This change also makes general references to C and C++ (the isoC and isoCPP glossary entries) point to C11 and C++11 respectively. We still have an explicit reference to C23 for integer value behaviors (C23 adopted two's compliement).
The intent of basing on C11 and …
=> Cleanup C++ references in the language spec

proposals/infra/INF-0001-availability-diagnostics.md
Proposal to add environment parameter to the Clang availability attribute and use it for per-stage availability annotations.
Also rename intrinsic -> function to keep the naming consistent.
Fixes #189
=> [INF-0001] Add environment parameter for per-stage availability annotations

specs/language/basic.tex, specs/language/conversions.tex
This just updates the conversion rank for minimum precision types which are now represented in the Basic.types section.
I've iterated on this a few times and reduced it down to just the min16{int|uint|float} types because those are the only types DXC actually supports. Using any of the other types produces a warning and they get treated as the corresponding min16 type.
The promotion orders are as follows:
min16int < int16_t < int32_t < int64_t
min16uint < uint16_t < uint32_t < uint64_t
min16float < half < float < double
=> Update conversion ranks for minimum precision types

proposals/0018-work-graphs.md
- Added text clarifying ALL_MEMORY behavior.
- Added note clarifying that using the new barrier intrinsic with equivalent arguments is not translated to the legacy DXIL op for lower shader model targets.
- Minor formatting adjustments.
Part of https://github.com/microsoft/DirectXShaderCompiler/issues/6538.
=> Minor clarifications to Barrier for ALL_MEMORY and equivalent forms

proposals/0017-conforming-literals.md
This adds wording to the specification to adopt Clang's -Wdouble-promotion warning group.
Resolves #220
=> Add -Wdouble-promotion warnings

proposals/0017-conforming-literals.md
This updates wording in the "Problems with this solution" section to reflect the confirmed problems caused by integer literals and the speculative problems relating to floating point precision and conversion ranks.
=> Add wording about conversion rank changes

docs/Process.md, proposals/templates/infrastructure-template.md
This clarifies details for the process docs for how proposals move through phases. This update also makes some small tweaks to the process for infrastructure proposals to optionally bypass the **Under Review** phase when outside feedback is not expected. This allows for a more expedited process for designs that only impact internal implementation details.
This also contains a few small updates to the infrastructure tempalte to have an optional link to LLVM's Discourse, and more clarification around documentation expectations.
=> Updates to process docs

specs/language/lex.tex
This adds a definition of floating literals that is consistent with existing HLSL documentation and other shader compilers. It is notably different from the implementations in DXC and FXC.
=> Expand definition of floating literals

proposals/0016-c-interface-compiler-library.md
This commit includes details about the dxcapi nano-COM library.  
The point of this change is to ensure that there is understanding of what is supported and supplied in today's compiler library before designing any c-style exports.
The approach taken:
* What features are in the dxcapi COM library?
* What form is the data being passed around?  How is it created/manipulated etc?
* How do I compile a shader?
* How do I access reflection data?
* What are the other parts
There are still some missing snippets that will need to be added (maybe).
* How to use the linker... and what scenarios is it used for?
* How to optimize a shader?
* How to use the include handler?
* Perhaps others..
=> Add details about existing nano-COM compiler library and include description of features and code snippet usage

specs/language/lex.tex
Adds a new chapter to describe the integer literal behavior as conforming to C. This documents the feature as proposed in:
https://github.com/microsoft/hlsl-specs/blob/main/proposals/0017-conforming-literals.md
=> Add Integer Literals chapter

specs/language/CMakeLists.txt
This adds a trivial table of contents to the HTML spec build. It isn't pretty but it works.
=> Add table of contents to HTML generation

proposals/0017-conforming-literals.md
This updates the specification to include additional warnings for diagnosing literal values that will change signedness.
=> Add new -Whlsl-legacy-literal warnings

specs/language/basic.tex, specs/language/macros.tex, specs/language/placeholders.tex
This specifies more of the basic language behaviors including declarations and definitions.
HLSL has some small implicit differences from C & C++ for declarations and definitions. Notably the handling of global variable declarations, which are implcitly const and external unless `static` is specified.
=> Add Basic.Decl

proposals/infra/INF-0002-root-signature-in-clang.md
This change adds an initial proposal for root signature handling in Clang.
This change proposes adding:
* New AST nodes to represent the root signature
* A metadata representation of the root signature so it can be stored in LLVM IR
* Validation and diagnostic generation for root signatures during semantic
analysis
* Conversion of the metadata representation to the binary serialized format.
=> [INF-0002] Add proposal for root signature handling in Clang

specs/language/hlsl.tex, specs/language/overloading.tex, specs/language/placeholders.tex
This captures the basic terminology and describes the situations in which a declaration is not overloadable.
There are a lot of similarities here with C++, but also a lot of unique HLSL behavior.
=> Begin writing overloading spec

specs/language/basic.tex, specs/language/introduction.tex, specs/language/lex.tex
Minor fixes in the HLSL language specification text.
=> Minor fixes, mostly typos

specs/language/conversions.tex, specs/language/overloading.tex, specs/language/placeholders.tex
This starts to flesh out more complete overload resolution rules. A lot of this is extremely similar to C++ however we have some key differences. Those differences include:
* HLSL supports overload resolution in 5 contexts, whereas C++ supports it in 7 (DXC actually only supports 2 of those contexts).
* HLSL has two additional conversion sequence ranks.
* HLSL has more rules to disambiguate some conversions.
=> [Overload.Res] Add overload resolution sections

specs/language/declarations.tex, specs/language/hlsl.tex, specs/language/placeholders.tex, specs/language/statements.tex
Create chapter file for Declarations and add section about linkage. Enumerate the language defaults and where it is implementation dependent. Add empty chapter file for Statements to preserve the chapter ordering.
=> Add Linkage section

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/proposal.md, .github/ISSUE_TEMPLATE/spec.md
This will get new issues automaticallly added to the triage board so I can stop doing it manually.
=> Add "needs-triage" keyword to templates

specs/language/conversions.tex, specs/language/overloading.tex
This change is a shift in how conversion sequences and overload scoring
is handled to disambiguate a few cases that DXC handles today through
simpler rules.
The main cases relate to scoring conversion sequences with dimension
adjustment conversions. With this change an implicit conversion sequence
is now defined as:
* Value conversion (lvalue to rvalue or array decay)
* Data conversion (int/float/bool/struct promotion or conversion)
* Dimension conversion (splat or truncate)
* CV qualifier conversion (add const)
Conversion sequences are still assigned the rank of their "highest"
conversion following the same chart as before where the ranks are:
* Exact match
* Scalar extension without promotion or conversion
* Promotion
* Scalar extension with promotion
* Conversion
* Scalar extension …
=> Simplify conversion sequences and overload scoring

specs/language/declarations.tex
Add `export` keyword to HLSL language specs.
The spec describes two ways the `export` keyword can be used.
1. On individual function declarations
```
export void f() {}
```
2. On a group of function declaration:
```
export {
void f1();
void f2() {}
}
```
DXC currently supports only the first case, but since Clang has support for both, we might as well support it in HLSL 202y too. 
This spec update does not yet include detailed rules for when a function can or cannot be exported, such as when it has resource argument or semantic annotations. That will be covered by llvm/llvm-project#93330.
This change also adds more sections under Declarations (based on C++ spec layout).
Contributes to: llvm/llvm-project#92812
=> Add `export` keyword to HLSL language spec

docs/Process.md, proposals/templates/extension-template.md
This updates the process docs to add a new documented "fast-track" process for introducing conforming extensions to HLSL.
This new process is intended to make it easy to quickly add vendor or platform specific extensions as long as they conform to the existing language definition.
=> Document Fast-track process

proposals/0011-inline-spirv.md
To be able to add the necessary capabilities and extensions for
SpirvTypes, we have to be able to add the capabilities and extension
attributes to the variables of that type. This change updates the inline
spirv spec to allows those changes.
Fixes #269
=> [0011] Allows cap and ext attributes on variable declarations

proposals/infra/INF-0004-validator-hashing.md
This proposal seeks to address user needs for building DirectX shaders on a wider variety of platforms than we can reasonably support through official releases, as well as the need for certain workflows to bypass the DXIL validator.
This proposal includes a plan for releasing the validator hashing algorithm into the DXC public repository, and includes the algorithms in the appendix.
Strategically this aligns the DXIL validator to fill a role more aligned with other virtual ISA validation tools.
=> [INF-0004] New proposal for validator hashing

specs/language/statements.tex
=> add a spec for loop unroll

specs/language/basic.tex, specs/language/declarations.tex
This is purely an editorial re-ordering. No changes in language just moving the section from Decl earlier to Basic so that other concepts in basic for specifying the program model will flow more naturally.
=> [Editorial] Move Decl.Linkage to Basic.Linkage

proposals/infra/INF-0004-register-types-and-diagnostics.md, proposals/infra/INF-0005-register-types-and-diagnostics.md
This PR adds a detailed specification for the register annotation diagnostic infrastructure, going into detail on the analysis and diagnostic emisison steps. It's a follow up PR of https://github.com/microsoft/hlsl-specs/pull/230
=> Complete detailed design in resource binding diagnostic infrastructure spec

specs/language/basic.tex
This adds language for determining if two types are _scalar layout compatible_ by defining a _scalarized representation_ which is a sequence of types that can then be compared.
The scalar representations of types will be used in several contexts throughout HLSL including:
* "Flattened" type casting
* Scalarized initiailization lists
* Defining additional type traits (homogeneous types)
=> Add scalar layout compatability trait

specs/language/basic.tex, specs/language/declarations.tex
This section is pretty bare bones, but it defines some of the basics for how program start is represented.
=> Add some basic language for program start

specs/language/basic.tex, specs/language/declarations.tex
The C++ specification talks in terms of module, external, internal, and no linkage. These linkages in C++ refer to translation units. For HLSL, we have some differences in how programs are built and linked that can't be fully expressed in that language.
Specifically, we have a notion of a program-export (entry functions, export keyword), that denotes a linkage that is more external than just cross translation unit.
This change introduces a term _program linkage_ to refer to names that have linkage outside a linked or freestanding program.
=> Introduce program linkage

proposals/0014-expanded-comparison-sampling.md
The comparison value was placed just after the locations in the implementation of SampleCmpBias and SampleCmpGrad. This moves the param in the spec to match.
=> Relocate cmp values for extended texture compares

proposals/0021-vk-coop-matrix.md
This propsal will expose the
[VK_KHR_cooperative_matrix](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_cooperative_matrix.html)
extension in HLSL.
=> Add proposal for Vulkan cooperative matrix

specs/language/conversions.tex
Previously the spec had allowed trunction conversions to produce cxvalues which enabled them to be used in output arguments. This is inconsistent with the DXC and FXC implementation, which disallows binding trunctions to output arguments.
The spec also previously did not allow trunction to scalar values. Initially that was excluded due to discussions around truncations and extensions of output arguments. Since DXC and FXC both disallow trunction in output arguments, it seems safe to support truncation to scalar here with a cooresponding warning.
This will allow the spec to more consistently align with the reference implementations.
This has no change to overload resolution except that a vector argument can be truncated to a scalar producing a Truncation, Truncation Promotion, or …
=> Clarifications and alignment of vector truncations

proposals/0020-hlsl-202x-202y.md, proposals/0022-hlsl-loop-unroll-factor.md, proposals/NNNN-hlsl-loop-unroll-factor.md
This PR gives an intro to the issue at hand, the motifications for unification and a proposed solution.
=> Add a proposal on how to handle the loop unroll factor in HLSL 202x

specs/language/overloading.tex
This wording went through a few iterations and it ended up in a silightly confused state. This just tries to simplify and clarify the ordering of the ranks.
=> Cleanup wording on ordering of conversion ranks

specs/language/expressions.tex
There are a few discrepancies between what I originally wrote here and what DXC does. These changes adjust to the actual behavior and more closely align with implicit conversion sequences.
Fixes #308
=> Revise Usual Arithmetic Conversions

specs/language/expressions.tex
This somewhat future proofs some aspects of the language here by saying that [in]out parmaeter initialization is copy-initialization, but the writeback assignment is _assignment_. That allows for clarity around overloaded operators so that the argument life becomse something like this:
```
auto &ArgTmp = (Arg); // Evaluate the argument expr saving it.
T Param = ArgTmp;     // Copy-initialize Param with Arg's result.
call(Param);          // Call the function.
ArgTmp = Param;       // Assign back the Param result with =.
```
=> Rework some wording around out and inout parameters

specs/language/hlsl.tex
Having overloading before declarations was wrong. This just moves the chapter later.
=> Move the Overloading chapter later

proposals/0010-vk-buffer-ref.md
The sample uses an invalid syntax for initializing a vk::BufferPointer.
This fixes up the syntax.
Fixes #322.
=> [0010] Fix constructor call

.github/pr-labels.yml, .github/workflows/pr-labeler.yml
This adds `needs-triage` to any PR that changes the proposals folder, which will cause it to appear on our triage board.
=> Add GitHub action to label proposal PRs

specs/language/declarations.tex
This one is a bit gnarly because it involves a lot of depth-first traversing of declarations, types, and initialization expresssions.
Questions and suggestions on how to clarify are greatly appreciated!
=> Start working on HLSL initialization lists

proposals/0024-opacity-micromaps.md
Inline raytracing needs to be aware OMMs may be used, just like non-inline raytracing does.  
Non-inline raytracing has RAYTRACING_PIPELINE_FLAG_ALLOW_OPACITY_MICROMAPS.  
But raytracing pipeline state doesn't apply to inline raytracing.  So for in the inline case, add a RAYQUERY_FLAG_ALLOW_OPACITY_MICROMAPS flag to the template parameters for instantiating the RayQuery object.
=> Add ALLOW_OPACITY_MICROMAPS template flag to RayQuery object

docs/DesignMeetingMinutes/2025-01-21.md
This PR adds the meeting minutes for the design meeting on 2025/01/21.
=> Design Meeting Minutes - 2025/01/21

proposals/infra/INF-0004-validator-hashing.md
Now that we know which AgilitySDK version will support hash bypass, the "TBD" in the spec can be replaced with the actual version. 
Also consider whether to move this out of "proposal" state, perhaps as soon as that AgilitySDK becomes available?  Actually might need to stay in proposal state until any DXC side changes are finished, such as publishing dxil.dll?
=> Update INF-0004-validator-hashing.md with applicable AgilitySDK version

.github/workflows/jekyll-gh-pages.yml
Apparently upload-pages-artifact v1 uses a depreacated version of upload-artifact. This gets our pipelines working again.
=> Update version of artifact uploader

proposals/0026-hlsl-long-vector-type.md, proposals/NNNN-dxil-vectors.md
This splits the spec into two. dxil-vectors concerns the addition of vectors to DXIL only. hlsl-long-vector-type relates to the addition of long vectors in the HLSL language and also for select DXIL intrinsics.
Throughout, this adds additional details concerning testing and support. It makes a few alterations to the originally proposed behavior particularly concerning the loading and storing of long vectors whether from/to raw buffers or groupshared variables. The latter intrinsics were dropped entirely in favor of existing assignment operations being lowered to appropriate operations.
Long vectors are allowed in structs and non-entry function signatures and disallowed in shader signatures, cbuffers/tbuffers, and as elements of non-raw buffers.
Note that the use of 6.9 is a placeholder …
=> Rework hlsl-vector-type into two specs

specs/language/lex.tex
I discovered this formatting error when looking reviewing this as a reference.
=> Fix missing newline in floating literal grammar

proposals/0027-shader-execution-reordering.md
As noted by @Jasper-Bekkers in [this comment](https://github.com/microsoft/hlsl-specs/pull/277#issuecomment-2616782435), "MaybeReorderThread" may a better name to make it clear that some implementations may not actually reorder threads at this point.
=> [0027] Shader Execution Reordering: rename "ReorderThread" to "MaybeReorderThread"

proposals/0029-cooperative-vector.md
This change makes the cooperative vector proposal focused on specifying the DXIL operations required to support cooperative vectors across a broad range of hardware architectures.
A future proposal will discuss the HLSL API without holding up acceptance of the DXIL operations.
This change also fixes some formatting and layout markdown issues.
=> [0029] Remove HLSL API from Cooperative Vector proposal

proposals/0029-cooperative-vector.md
Replace the "TBD" with a link to proposal 0031.
=> [0029] Fix link to the API proposal

proposals/0024-opacity-micromaps.md
No validation mask is needed for the new OMM flags. Source level validation is still needed to ensure the flags are used correctly, but the validator will not need to run the flags through a mask to validate them. Additionally, this PR removes any mention of flag value validation, except for one specific case where a RayQuery ray flag template argument necessitates the RayQuery ray query flag template argument's value. 
This PR updates the spec to reflect new changes to the validator, and proposes some new diagnostics with the new RAYQUERY_FLAG_ALLOW_OPACITY_MICROMAPS flag. It defines a new DXIL OP, `AllocateRayQuery2`, which will be generated when RayQuery is given a 2nd, optional, ray query template flag argument in HLSL. 
This PR is a transfer from …
=> [OMM] Remove validation masking, update spec

proposals/0027-shader-execution-reordering.md
- Require devices that support SM 6.9 and raytracing to support SER, whether it can reorder or not.  If not, ReorderThread() is just a no-op.
- Expose D3D runtime cap indicating BOOL ShaderExecutionReorderingActuallyReorders
- Example of using SER to just TraceRay without Invoke() as a way to just get T value from the HitObject without running ClosestHit/Miss. This works on any device.
=> Require SER support on any SM 6.9 device with raytracing support.

proposals/0029-cooperative-vector.md
Previously, the spec used defined a new enum value to describe how to interpret vectors stored in memory. 
This enum was very similar to ComponentType.
This change makes it so that instead new values are added to ComponentType where necessary, and documents which values are valid in various contexts.  The D3D enum is updated to align with ComponentType.
Closes #402
=> [0029] Extend ComponentType for interpretations

proposals/0029-cooperative-vector.md
This is an attempt to resolve #399 and #413 in a way that's consistent with existing DXIL opcodes.
* use the existing `SignedOpKind` enum to determine signedness.  Main difference that this inverts the current meaning of this argument, but it brings it inline with other DXIL operations where `0` means float/signed and `1` means unsigned.
* add a new argument for specifying the input vector signedness.
This deliberately doesn't add a general-purpose flags argument. Rationale:
* YAGNI
* if we want to add new flags we should define a new operation that accepts the new flags so the list of accepted flags can be determine just be looking at the opcode
Resolves #413 
Resolves #399
Resolves #414
=> [0029] Use "SignedOpKind" enum to indict input/ouput vector signedness

proposals/0029-cooperative-vector.md
CooperativeVectors as a name won't integrate very well with expected future feature (e.g. CooperativeMatrix).   
In hlsl these are a set of dx::linalg:: operations, so "cooperative vector" doesn't appear.   And accordingly from the D3D API point of view it seems better to organize under a common LINEAR_ALGEBRA umbrella, referrubg to CooperativeVectors as LINEAR_ALGEBRA_MATRIX_VECTOR_*.
So this PR does the rename.  
Some types became *_LINEAR_ALGEBRA_MATRIX_VECTOR*.
Some types became just *_LINEAR_ALGEBRA_* with the assumption they apply equally when MatMat operations come along.  
Reviewers please check I made the correct scoping choices for each name.  In particular I'm not sure about the training/inference ones.
=> [0029] Rename COOPERATIVE_VECTOR D3D APIs to LINEAR_ALGEBRA

proposals/0007-const-instance-methods.md, proposals/0007-const-member-functions.md
I started digging a bit into this in DXC and identified a lot of cross-cutting issues that we need to consider in this.
This change updates the proposal to flesh out the behavior and related issues around HLSL const-correctness.
This does identify some source-breaking changes that this would introduce as well as some behavior changes that I think we should introduce in the HLSL built-in types.
=> [0007] Big update to flesh out const instance methods

docs/DesignMeetingMinutes/2025-03-18.md
This PR adds the stub meeting minutes as an agened for the 3/18/2025 design meeting.
=> 2025-03-18 Design Meeting Agenda & Minutes

specs/language/CMakeLists.txt
The first time generates the PDF with incomplete references, the second time fills it out with the full references.
=> Run pdflatex twice

proposals/0029-cooperative-vector.md
I noticed that these comments weren't lining up with what Intellisense was telling me the actual values were.
=> [0029] Fix ComponentType numbering comments

proposals/0027-shader-execution-reordering.md
There is currently no way to specify HitKind for a HitObject created from RayQuery with COMMITTED_PROCEDURAL_PRIMITIVE_HIT and custom attributes. This PR adds another parameter to the call to allow this.
=> [SER] Add CommittedCustomHitKind to HitObject::FromRayQuery

proposals/0029-cooperative-vector.md
LinearAlgebraConvertMatrix() is a D3D commandList method.  This change outlines interactions with command list infrastructure, in particular interaction with barriers.
=> [0029] Define commandList interactions for LinearAlgebraConvertMatrix() [no HLSL/DXIL impact]

.github/workflows/pr-description-checker.yml
This adds a github action to verify that PR descriptions are not empty. We have this on DXC to enforce our policy and should have it here as well.
=> Add PR description checker to hlsl-specs

proposals/0029-cooperative-vector.md
Tier checks should use >=, otherwise the feature will suddenly be disabled when new functionality arrives. Sample code should get this right so people copying it into their own apps get the right behavior by default.
=> [0029] Fix sample code tier check

proposals/0029-cooperative-vector.md
=> [0029] Fix description of OuterProductAccumulate

proposals/0024-opacity-micromaps.md
This PR updates the spec given a rear-view perspective after having implemented the OMM feature. It removes undesired language concerning validation masks, and solidifies the diagnostic checking approach to the availability attribute mechanism, while making some small nits here and there.
It should be noted that RDAT information pulled from HLSL Subobjects is tested, but not using the D3DReflect part of FileCheckerTest. This is because the subobject data is lost due to how filecheck processes the compiled output. We instead run tests by checking the subobject dump in the disassembly comments. So, language referring to testing the feature using D3Dreflect has been changed to more accurately reflect the alternative methods used in testing the feature.
=> Remove validation mask language, update spec given implementation knowledge

proposals/0031-hlsl-vector-matrix-operations.md
Although these "builtins" are not intended to be part of the HLSL language, and
no promises are made that these will continue to be available over time, this
proposal describes an implementation in terms of builtins such as this. For
this reason it is useful to have them described here as a reference point.
Each builtin corresponds to one of the operations described in [0029].
[0029]: 0029-cooperative-vector.md
----
For this review, I'm keen on feedback for whether or not this is a good way to describe the builtins?  At the moment they're HLSL code that I know can compile, but that might mean they've picked up HLSL-isms that don't necessarily apply to a specification of a builtin.
=> [0031] Add builtins

proposals/0001-hlsl-namespace.md, proposals/0002-cxx-attributes.md, proposals/0004-unions.md, proposals/0005-strict-initializer-lists.md, proposals/0006-reference-types.md, proposals/0008-non-member-operator-overloading.md, proposals/0009-math-modes.md, proposals/0020-hlsl-202x-202y.md, proposals/0022-hlsl-loop-unroll-factor.md
This updates our current in-tree proposals for the correct language version targets.
I've moved everything except proposal 0003, 0017 and 0022 into 202y since we almost certainly won't be taking any of those into 202x.
I've also updated proposal 0020 with updated language around 202x and 202y reflecting my latest thinking. I've expanded the 202y documentation to discuss the major themes that are driving current likely 202y features and the associated breaking behavior changes.
=> [202x][202y] Update proposals for correct targets

docs/DesignMeetingMinutes/2025-02-18.md
This PR represents the planned agenda for the 2025-02-18 design meeting and will become the meeting minutes after the meeting occurs.
=> 2025-02-18 Design Meeting Agenda & Minutes

proposals/0029-cooperative-vector.md
It wasn't clear exactly what "inferencing optimal" or "training optimal" referred to and whether or not the scope for these extended beyond the operations described here.  This changes makes this more clear associating the layouts with the operations they apply to.
InferencingOptimal -> MulOptimal
TrainingOptimal -> OuterProductOptimal
=> [0029] Rename optimal matrix layouts to match operations

proposals/0027-shader-execution-reordering.md
Remove HitObject_ObjectToWorld4x3 and HitObject_WorldToObject4x3 for consistency with existing intrinsics. DXIL only specifies opcodes for 3x4 and the result is transposed where required by HLSL.
Fixes #477
=> [0027] Remove HitObject_ObjectToWorld4x3 and HitObject_WorldToObject4x3

proposals/0029-cooperative-vector.md
This doesn't change the specified behavior of these parameters, but is easier to follow since `i1`s are printed as `true` and `false` and, while implementing the feature, it made more sense to use simple booleans.
=> [0029] Make "input signed op kind"s be "is input unsigned" and booleans

proposals/0034-vk-sampled-texture.md, proposals/NNNN-vk-sampled-texture.md
This proposal adds a set of `vk::SampledTexture*` types to represent SPIR-V's sampled image types. The intent is to replace and deprecate the `[[vk::combinedImageSampler]]` annotation.
I have created this with the extension template with the intent of using the fast-track process, as this is a platform-specific feature that is already supported by all Vulkan hardware and drivers, and it does not change any existing language behavior.
=> [202x] Propose adding vk::SampledTexture* types

proposals/infra/INF-0005-validator-backcompat-testing.md, proposals/infra/INF-NNNN-validator-backcompat-testing.md
We want to make the internal validator the default one, but this impacts how we test that we haven't broken DXIL.  This proposal suggests a way to move these tests into the public github and how to modify DXC and the build system to run the tests.
=> First pass at validator backcompat testing proposal

specs/language/declarations.tex
Add language specification text for arrays of unknown size.
=> [Decl.Init.Agg] Arrays of unknown size

proposals/0035-linalg-matrix.md, proposals/NNNN-linalg-matrix.md
This is more as a straw man to start discussion than an actual proposal we'll move forward with as it is. This is a clear gap in the Direct3D and core HLSL feature sets and we should seek to address it.
=> Introduce really rough linalg matrix proposal

proposals/0010-vk-buffer-ref.md, proposals/0012-psv0-entry-name.md, proposals/0017-conforming-literals.md, proposals/0021-vk-coop-matrix.md, proposals/0022-hlsl-loop-unroll-factor.md, proposals/0023-cxx11-base.md, proposals/0028-dxil18.md
* 0010: add a missing proposal line and fix some formatting
* 0012: mark as completed
* 0017: mark as completed, fix links
* 0021: mark as completed
* 0022: fix formatting
* 0023: fix link
* 0028: mark as completed
=> [0010][0012][0017][0021][0022][0023][0028] Housekeeping for proposals

proposals/0004-unions.md
This fleshes out the language design for union types.
Resolves #38, resolves #523
=> [0004] Adding spec language for unions

proposals/0038-16bit-isspecialfloat.md
Mention how min16float type will be handled in the 16 bit isSpecialFloat dxil op proposal; the IR generated for it should remain unchanged.
=> [0038] Mention handling of min16float type in isSpecialFloat 16 bit DXIL Op proposal

proposals/0035-linalg-matrix.md
This is a big revision to the `linalg::Matrix` proposal. There are a few substantial changes in this proposal to the API formulation.
First it updates the `Matrix` template so that the component type is specified as an enumeration rather than an explicit type. This allows specifying matrix types that are not HLSL built-in types.
Second, it adds two new arguments to the `Matrix` template: `Use` and `Scope`. The `MatrixUse` enumeration specifies the type of matrix as an `A`, `B`, or `Accumulator`. This aligns with the Vulkan cooperative_matrix naming rather than the earlier DirectX `Left` and `Right` naming in an effort to be less confusing to users who are supporting both platforms. The additional `MatrixScope` enumeration denotes the scope of uniformity that the matrix value is operating …
=> [0035] `linalg::Matrix` detailed design revision

proposals/infra/INF-0006-Long-Vector-ExecutionTest-Plan.md
There was a collision between two proposals taking INF-0005, move the second landed one to INF-0006
=> [INF-0006][NFC] Fix proposal name collision

proposals/0030-dxil-vectors.md
Fixes #532
- Adds more dxil ops that fit the elementwise requirements
- confirms support for shufflevector
- Removes unnecessary bitcasts
=> [0030] Update DXIL Ops supported by Long Vectors

proposals/0026-hlsl-long-vector-type.md
Fixes #543 
Updates the spec to explicitly state that `Load`/`Store` of a vector into/out of a Raw Buffer requires alignment of the underlying buffer and that consuming APIs are allowed to further restrict alignment.
=> [0026] Clarify Buffer Memory layout

proposals/0030-dxil-vectors.md
Fixes #482
Adds `and`/`or` DXIL intrinsics to DXIL Vector spec
=> [0030] Add DXIL intrinsics for boolean vector reduction

docs/DesignMeetingMinutes/2025-07-22.md
Add the meeting minutes for the 2025-07-22 meeting. This includes calls to accept proposals 0004, 0007, and 0008 to HLSL 202y.
=> Meeting minutes for 2025-07-22

proposals/infra/INF-0006-Long-Vector-ExecutionTest-Plan.md
Adding some notes about the basic op type (unary, binary, or ternary). And some notes about output parameters where applicable.
=> Some updates to Long Vector Execution Test Plan tables

proposals/0027-shader-execution-reordering.md
Instead of templated Load pattern.
Closes #495
DXC change: https://github.com/microsoft/DirectXShaderCompiler/pull/7606
=> [0027] Change HitObject::GetAttributes to use out udt param

proposals/0035-linalg-matrix.md
This PR adds support for thread group scope matrices to the specification.
See Issue #577.
=> [0035] Add `MatrixScope::ThreadGroup`

proposals/0043-groupshared-arguments.md, proposals/NNNN-groupshared-arguments.md
This new proposal seeks to address a limitation in the HLSL language that prevents the HLSL standard library from being implementable in HLSL.
=> Add proposal for `groupshared` arguments

proposals/0031-hlsl-vector-matrix-operations.md
The functionality provided by this proposal is now being exposed through [0035-linalg-matrix.md](0035-linalg-matrix.md).
See https://devblogs.microsoft.com/directx/shader-model-6-9-and-the-future-of-cooperative-vector/ for more context.
=> [0031] Mark the HLSL Vector Matrix Operations proposal as rejected

proposals/0035-linalg-matrix.md
This PR replaces `Matrix::OuterProductAccumulate()` with `linalg::OuterProduct()` and `Matrix::Accumulate()`.  The objective with this change is to support a method for OuterProduct and Accumulate for Thread scope matrices.  It also extends the `MatrixLayout` enumeration and adds constraints for their usage.
=> [0035] Re-add support for OuterProduct and Accumulate for Thread Scope Matrices

proposals/0035-linalg-matrix.md
This adds some size constriants for matrices in the HLSL types as well as a draft for how the matrix shapes and types will be captured in the PSV runtime information for the D3D runtime to inspect.
Fixes #586
=> [0035] Matrix dimensions HLSL and container handling

proposals/0045-clustered-geometry.md, proposals/NNNN-clustered-geometry.md
Replaces #560 and #561 with a merged spec.
Replaces sponsor.
This one in particular should be pretty straightforward, it's just a scalar accessor that follows the existing patterns for all other raytracing scalar accessors.
=> [NNNN] ClusterID() support
