specs/language/glossary.tex, specs/language/introduction.tex
These are pretty small wording adjustments to improve clarity based on review feedback from @pow2clk in #10. I've created this as a separate PR because my previous one became orphaned when the repo went public.
=> Clarifying glossary and introduction

proposals/0010-vk-buffer-ref.md
=> Add pseudo-class definition to vk::BufferPointer spec

proposals/0010-vk-buffer-ref.md
=> Add feature check for vk::BufferPointer

specs/language/expressions.tex, specs/language/hlsl.tex
This change starts specifying HLSL expressions. The first bit goes through some bits about operator overloading and the usual aritimetic conversions.
=> Start on expressions

proposals/0011-inline-spirv.md
This begins the review period as described in #96.
=> [0011] Begin Review Period

proposals/0010-vk-buffer-ref.md
=> [0010] Fix buffer address space to be Vulkan device address space.

proposals/0012-psv0-entry-name.md
=> [0012] Change Status to Accepted

proposals/0010-vk-buffer-ref.md
Reformatting the proposal document. Trying to follow the suggestion in the template.
https://github.com/microsoft/hlsl-specs/blob/main/proposals/templates/basic-template.md#instructions
=> [0010] Reformat the buffer pointer proposal

proposals/0010-vk-buffer-ref.md
All outstanding issues for the vk::BufferPointer proposal are resolved. This proposal is accepted and ready for implementation.
=> [0010] Mark proposal as accepted!

specs/language/introduction.tex
This applies the feedback from PR #130 in this comment:
https://github.com/microsoft/hlsl-specs/pull/130#discussion_r1412549773
=> Apply feedback from #130

proposals/0014-expanded-comparison-sampling.md
This proposal was added without assigning a number.  This assigns the next number.
=> Assign 0014 to expanded-comparison-sampling proposal

proposals/0013-wave-size-range.md, proposals/0014-expanded-comparison-sampling.md, proposals/0015-extended-command-info.md
Sets status of Shader Model 6.8 features to complete: Wave Size Range, Expanded Comparison Sampling, and Extended Command Info
Also sets version field in place of "Planned" version
=> Update 6.8 features to complete

proposals/0015-extended-command-info.md
Update the device capability section for ExtendedCommandInfo
=> Update 0015-extended-command-info.md to reflect what we shipped.

proposals/0020-hlsl-202x-202y.md, proposals/infra/INF-NNNN-hlsl-202x-202y.md
I've talked about 202x and 202y in passing but haven't really written down my thoughts. This proposal is the start of writing down how I think we should classify the two language versions.
=> Add a proposal to describe 202x and 202y

proposals/0017-conforming-literals.md
This adds the details for the C integer literal rules that this proposal intends to adopt.
=> [0017] Update proposal with details on integers

proposals/0017-conforming-literals.md
Mitigations for the impact of this change will be the introduction of new diagnostics and reliance on existing diagnostics.
Fixes #183, fixes #184
=> [0017] Add proposal for mitigations

proposals/0017-conforming-literals.md
This begins the review period for proposal 0017.
Please provide feedback either on issue #211, or by filing new issues and referencing proposal 0017.
Related #211.
=> [0017] Begin Review Period

proposals/0017-conforming-literals.md
The review period has concluded and all issues have been resolved. There are no remaining outstanding issues, so this proposal is now accepted for HLSL 202x.
Resolves #211
=> [0017] Mark proposal as accepted

proposals/infra/INF-0002-root-signature-in-clang.md
Fix the comment in resource not fully bound example.
=> [INF-0002] fix comment about resource not fully bound.

proposals/infra/INF-0005-register-types-and-diagnostics.md
We already have an INF-0004 proposal, so this should be INF-0005, and the starting raw tag was deleted which caused the GitHub pages build to fail.
=> Fix INF proposal numbering and pages build

.github/workflows/pr-labeler.yml
It needs to checkout the repo before it can run the labeler.
=> Fix PR Labeler

.github/pr-labels.yml, .github/workflows/pr-labeler.yml
This is such a pain to deal with, but I setup a test bed in my fork and verified that this actually really works this time.
Here's the link to my test PR: https://github.com/llvm-beanz/hlsl-specs/pull/3
=> Really really this time fix pr-labeler (I swear)

docs/DesignMeetingMinutes/2025-02-04.md
This adds the meeting minutes for the 2025-02-04 design meeting.
=> [Design Meeting] Add meeting minutes for 2025-02-04

proposals/0029-cooperative-vector.md
Add note that this is targetting shader model 6.9.
=> [0029] Set cooperative vectors proposal to under review

proposals/0029-cooperative-vector.md
* CheakFeatureSupport -> CheckFeatureSupport
* Add link to API proposal next to the sample code
=> [0029] Fix some typos, add link to API proposal

.github/workflows/jekyll-gh-pages.yml
Wow... this has been broken forever... fun.
=> Check out the PR head ref

proposals/0031-hlsl-vector-matrix-operations.md
This fills in the broad-strokes proposal for the cooperative vectors API.
=> [0031] Add Initial proposal for cooperative vectors API

proposals/0027-shader-execution-reordering.md
In the DXIL section, specify how reordercoherent is encoded.
=> [SER] Specify how reordercoherent is encoded

proposals/0029-cooperative-vector.md
=> [0029] Fix parameter ordering

proposals/0029-cooperative-vector.md
=> [0029] Fix broken links

proposals/0027-shader-execution-reordering.md
=> [0027] Put SER HLSL additions under dx namespace.

proposals/NNNN-dxil19.md
This adds a single entry point for all the new SM 6.9 features added to DXIL 1.9.
=> Add a DXIL 1.9 summary proposal

proposals/0029-cooperative-vector.md, proposals/0031-hlsl-vector-matrix-operations.md
https://github.com/microsoft/hlsl-specs/issues/492
=> [0029][0031]Add Matrix Layout constraint to OuterProductOptimal for OuterProductAccumulate function

proposals/0029-cooperative-vector.md
This attempts to replicate the spirit of the original sample, but using the actual API as described in proposal 0031.
=> [0029] Update example code to use real API

docs/DesignMeetingMinutes/2025-04-29.md
Add meeting minutes and agenda for 2025/04/29 design meeting.
=> Design meeting agenda and minutes for 2025-04-29

proposals/0029-cooperative-vector.md
Just minor typos I noticed while reading.
=> [0029] Minor typos in cooperative vector proposal

proposals/0029-cooperative-vector.md
Just addressing some very minor issues I noticed while reviewing this proposal.
=> Minor grammar/typo fixes

.github/update_proposal_front_matter.py
* Handle the reference-style links used in proposal 0029
* Handle "Sponsor(s)", as used in proposal 0010
* Add a "--overwrite" flag to help with testing
=> Fixes for extracting metadata from proposals

proposals/0035-linalg-matrix.md
This is a slightly big update to clean up the HLSL pseudo implementaiton. I've added a few example usage bits and added a full HLSL implementation in an appendix.
Resolves #583
=> [0035] Updates to the linalg::matrix proposal

docs/DesignMeetingMinutes/2025-05-27.md
This adds the design meeting minutes for 2025-05-27.
=> Design meeting minutes for 2025-05-27

docs/DesignMeetingMinutes/2025-07-08.md
Add design meetings for 2025-07-08.
=> Design meeting minutes for 2025-07-08

proposals/0027-shader-execution-reordering.md
=> [0027] Clearer non-hit matrix definition

proposals/0038-16bit-isspecialfloat.md
This proposal has been accepted and is in the process of being implemented.
=> [0038] Change status from 'Under Consideration' to 'Accepted'

proposals/infra/INF-0005-validator-backcompat-testing.md
This proposal is in the process of being implemented.
=> [INF-0005] Change status from 'Under Consideration' to 'Accepted' 

proposals/0042-restricted-unbounded-arrays.md
After the meeting today we seem to have alignment here. I'm going to mark this proposal as under review with PR #634 as the main review for the spec contribution.
=> [0042] Mark as under review
